version: 3
tasks:
  build:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -ldflags "-X github.com/018bf/example.Version={{ .version }}" -v -o ./dist/example ./cmd/example
    vars:
      version:
        sh: git describe --tags --abbrev=0

  test:
    cmds:
      - go test -cover ./... -coverprofile ./coverage.out -coverpkg ./...
      - defer: rm ./coverage.out
      - go tool cover -func ./coverage.out

  lint:
    cmds:
      - golangci-lint run ./... --timeout 5m0s

  clean:
    cmds:
      - golangci-lint run ./... --fix

  log:
    cmds:
      - git-chglog --config docs/.chglog/config.yml --output docs/CHANGELOG.md --next-tag {{ .tag }}

  release:
    deps:
      - task: lint
      - task: test
    cmds:
      - git flow release start {{ .tag }}
      - task: log
      - git add .
      - git commit -m "bumped the version number"
      - git flow release finish {{ .tag }} -f docs/CHANGELOG.md -p --showcommands
