// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/interceptors (interfaces: ApproachInterceptor)

// Package mock_interceptors is a generated GoMock package.
package mock_interceptors

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockApproachInterceptor is a mock of ApproachInterceptor interface.
type MockApproachInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockApproachInterceptorMockRecorder
}

// MockApproachInterceptorMockRecorder is the mock recorder for MockApproachInterceptor.
type MockApproachInterceptorMockRecorder struct {
	mock *MockApproachInterceptor
}

// NewMockApproachInterceptor creates a new mock instance.
func NewMockApproachInterceptor(ctrl *gomock.Controller) *MockApproachInterceptor {
	mock := &MockApproachInterceptor{ctrl: ctrl}
	mock.recorder = &MockApproachInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApproachInterceptor) EXPECT() *MockApproachInterceptorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockApproachInterceptor) Create(arg0 context.Context, arg1 *models.ApproachCreate, arg2 *models.User) (*models.Approach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Approach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockApproachInterceptorMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApproachInterceptor)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockApproachInterceptor) Delete(arg0 context.Context, arg1 string, arg2 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApproachInterceptorMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApproachInterceptor)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockApproachInterceptor) Get(arg0 context.Context, arg1 string, arg2 *models.User) (*models.Approach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Approach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApproachInterceptorMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApproachInterceptor)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockApproachInterceptor) List(arg0 context.Context, arg1 *models.ApproachFilter, arg2 *models.User) ([]*models.Approach, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.Approach)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockApproachInterceptorMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApproachInterceptor)(nil).List), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockApproachInterceptor) Update(arg0 context.Context, arg1 *models.ApproachUpdate, arg2 *models.User) (*models.Approach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Approach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockApproachInterceptorMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApproachInterceptor)(nil).Update), arg0, arg1, arg2)
}
