// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/interceptors (interfaces: AuthInterceptor)

// Package mock_interceptors is a generated GoMock package.
package mock_interceptors

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthInterceptor is a mock of AuthInterceptor interface.
type MockAuthInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockAuthInterceptorMockRecorder
}

// MockAuthInterceptorMockRecorder is the mock recorder for MockAuthInterceptor.
type MockAuthInterceptorMockRecorder struct {
	mock *MockAuthInterceptor
}

// NewMockAuthInterceptor creates a new mock instance.
func NewMockAuthInterceptor(ctrl *gomock.Controller) *MockAuthInterceptor {
	mock := &MockAuthInterceptor{ctrl: ctrl}
	mock.recorder = &MockAuthInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthInterceptor) EXPECT() *MockAuthInterceptorMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockAuthInterceptor) Auth(arg0 context.Context, arg1 models.Token) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockAuthInterceptorMockRecorder) Auth(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockAuthInterceptor)(nil).Auth), arg0, arg1)
}

// CreateToken mocks base method.
func (m *MockAuthInterceptor) CreateToken(arg0 context.Context, arg1 *models.Login) (*models.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", arg0, arg1)
	ret0, _ := ret[0].(*models.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAuthInterceptorMockRecorder) CreateToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockAuthInterceptor)(nil).CreateToken), arg0, arg1)
}

// RefreshToken mocks base method.
func (m *MockAuthInterceptor) RefreshToken(arg0 context.Context, arg1 models.Token) (*models.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", arg0, arg1)
	ret0, _ := ret[0].(*models.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthInterceptorMockRecorder) RefreshToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthInterceptor)(nil).RefreshToken), arg0, arg1)
}

// ValidateToken mocks base method.
func (m *MockAuthInterceptor) ValidateToken(arg0 context.Context, arg1 models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthInterceptorMockRecorder) ValidateToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuthInterceptor)(nil).ValidateToken), arg0, arg1)
}
