// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/interceptors (interfaces: DayInterceptor)

// Package mock_interceptors is a generated GoMock package.
package mock_interceptors

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDayInterceptor is a mock of DayInterceptor interface.
type MockDayInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockDayInterceptorMockRecorder
}

// MockDayInterceptorMockRecorder is the mock recorder for MockDayInterceptor.
type MockDayInterceptorMockRecorder struct {
	mock *MockDayInterceptor
}

// NewMockDayInterceptor creates a new mock instance.
func NewMockDayInterceptor(ctrl *gomock.Controller) *MockDayInterceptor {
	mock := &MockDayInterceptor{ctrl: ctrl}
	mock.recorder = &MockDayInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDayInterceptor) EXPECT() *MockDayInterceptorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDayInterceptor) Create(arg0 context.Context, arg1 *models.DayCreate, arg2 *models.User) (*models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDayInterceptorMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDayInterceptor)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockDayInterceptor) Delete(arg0 context.Context, arg1 models.UUID, arg2 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDayInterceptorMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDayInterceptor)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockDayInterceptor) Get(arg0 context.Context, arg1 models.UUID, arg2 *models.User) (*models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDayInterceptorMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDayInterceptor)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockDayInterceptor) List(arg0 context.Context, arg1 *models.DayFilter, arg2 *models.User) ([]*models.Day, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.Day)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDayInterceptorMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDayInterceptor)(nil).List), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDayInterceptor) Update(arg0 context.Context, arg1 *models.DayUpdate, arg2 *models.User) (*models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDayInterceptorMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDayInterceptor)(nil).Update), arg0, arg1, arg2)
}
