// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/interceptors (interfaces: EquipmentInterceptor)

// Package mock_interceptors is a generated GoMock package.
package mock_interceptors

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockEquipmentInterceptor is a mock of EquipmentInterceptor interface.
type MockEquipmentInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockEquipmentInterceptorMockRecorder
}

// MockEquipmentInterceptorMockRecorder is the mock recorder for MockEquipmentInterceptor.
type MockEquipmentInterceptorMockRecorder struct {
	mock *MockEquipmentInterceptor
}

// NewMockEquipmentInterceptor creates a new mock instance.
func NewMockEquipmentInterceptor(ctrl *gomock.Controller) *MockEquipmentInterceptor {
	mock := &MockEquipmentInterceptor{ctrl: ctrl}
	mock.recorder = &MockEquipmentInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEquipmentInterceptor) EXPECT() *MockEquipmentInterceptorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEquipmentInterceptor) Create(arg0 context.Context, arg1 *models.EquipmentCreate, arg2 *models.User) (*models.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEquipmentInterceptorMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEquipmentInterceptor)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockEquipmentInterceptor) Delete(arg0 context.Context, arg1 models.UUID, arg2 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEquipmentInterceptorMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEquipmentInterceptor)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockEquipmentInterceptor) Get(arg0 context.Context, arg1 models.UUID, arg2 *models.User) (*models.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEquipmentInterceptorMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEquipmentInterceptor)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockEquipmentInterceptor) List(arg0 context.Context, arg1 *models.EquipmentFilter, arg2 *models.User) ([]*models.Equipment, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.Equipment)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockEquipmentInterceptorMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEquipmentInterceptor)(nil).List), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockEquipmentInterceptor) Update(arg0 context.Context, arg1 *models.EquipmentUpdate, arg2 *models.User) (*models.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEquipmentInterceptorMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEquipmentInterceptor)(nil).Update), arg0, arg1, arg2)
}
