// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/usecases (interfaces: ArchUseCase)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockArchUseCase is a mock of ArchUseCase interface.
type MockArchUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockArchUseCaseMockRecorder
}

// MockArchUseCaseMockRecorder is the mock recorder for MockArchUseCase.
type MockArchUseCaseMockRecorder struct {
	mock *MockArchUseCase
}

// NewMockArchUseCase creates a new mock instance.
func NewMockArchUseCase(ctrl *gomock.Controller) *MockArchUseCase {
	mock := &MockArchUseCase{ctrl: ctrl}
	mock.recorder = &MockArchUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchUseCase) EXPECT() *MockArchUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockArchUseCase) Create(arg0 context.Context, arg1 *models.ArchCreate) (*models.Arch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Arch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockArchUseCaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockArchUseCase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockArchUseCase) Delete(arg0 context.Context, arg1 models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArchUseCaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArchUseCase)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockArchUseCase) Get(arg0 context.Context, arg1 models.UUID) (*models.Arch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Arch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockArchUseCaseMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockArchUseCase)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockArchUseCase) List(arg0 context.Context, arg1 *models.ArchFilter) ([]*models.Arch, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Arch)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockArchUseCaseMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockArchUseCase)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockArchUseCase) Update(arg0 context.Context, arg1 *models.ArchUpdate) (*models.Arch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*models.Arch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockArchUseCaseMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArchUseCase)(nil).Update), arg0, arg1)
}
