// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/usecases (interfaces: DayUseCase)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDayUseCase is a mock of DayUseCase interface.
type MockDayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDayUseCaseMockRecorder
}

// MockDayUseCaseMockRecorder is the mock recorder for MockDayUseCase.
type MockDayUseCaseMockRecorder struct {
	mock *MockDayUseCase
}

// NewMockDayUseCase creates a new mock instance.
func NewMockDayUseCase(ctrl *gomock.Controller) *MockDayUseCase {
	mock := &MockDayUseCase{ctrl: ctrl}
	mock.recorder = &MockDayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDayUseCase) EXPECT() *MockDayUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDayUseCase) Create(arg0 context.Context, arg1 *models.DayCreate) (*models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDayUseCaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDayUseCase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDayUseCase) Delete(arg0 context.Context, arg1 models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDayUseCaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDayUseCase)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockDayUseCase) Get(arg0 context.Context, arg1 models.UUID) (*models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDayUseCaseMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDayUseCase)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockDayUseCase) List(arg0 context.Context, arg1 *models.DayFilter) ([]*models.Day, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Day)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDayUseCaseMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDayUseCase)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockDayUseCase) Update(arg0 context.Context, arg1 *models.DayUpdate) (*models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDayUseCaseMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDayUseCase)(nil).Update), arg0, arg1)
}
