// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/usecases (interfaces: EquipmentUseCase)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockEquipmentUseCase is a mock of EquipmentUseCase interface.
type MockEquipmentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockEquipmentUseCaseMockRecorder
}

// MockEquipmentUseCaseMockRecorder is the mock recorder for MockEquipmentUseCase.
type MockEquipmentUseCaseMockRecorder struct {
	mock *MockEquipmentUseCase
}

// NewMockEquipmentUseCase creates a new mock instance.
func NewMockEquipmentUseCase(ctrl *gomock.Controller) *MockEquipmentUseCase {
	mock := &MockEquipmentUseCase{ctrl: ctrl}
	mock.recorder = &MockEquipmentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEquipmentUseCase) EXPECT() *MockEquipmentUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEquipmentUseCase) Create(arg0 context.Context, arg1 *models.EquipmentCreate) (*models.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEquipmentUseCaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEquipmentUseCase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockEquipmentUseCase) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEquipmentUseCaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEquipmentUseCase)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockEquipmentUseCase) Get(arg0 context.Context, arg1 string) (*models.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEquipmentUseCaseMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEquipmentUseCase)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockEquipmentUseCase) List(arg0 context.Context, arg1 *models.EquipmentFilter) ([]*models.Equipment, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Equipment)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockEquipmentUseCaseMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEquipmentUseCase)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockEquipmentUseCase) Update(arg0 context.Context, arg1 *models.EquipmentUpdate) (*models.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*models.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEquipmentUseCaseMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEquipmentUseCase)(nil).Update), arg0, arg1)
}
