// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/usecases (interfaces: MarkUseCase)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMarkUseCase is a mock of MarkUseCase interface.
type MockMarkUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockMarkUseCaseMockRecorder
}

// MockMarkUseCaseMockRecorder is the mock recorder for MockMarkUseCase.
type MockMarkUseCaseMockRecorder struct {
	mock *MockMarkUseCase
}

// NewMockMarkUseCase creates a new mock instance.
func NewMockMarkUseCase(ctrl *gomock.Controller) *MockMarkUseCase {
	mock := &MockMarkUseCase{ctrl: ctrl}
	mock.recorder = &MockMarkUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarkUseCase) EXPECT() *MockMarkUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMarkUseCase) Create(arg0 context.Context, arg1 *models.MarkCreate) (*models.Mark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Mark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMarkUseCaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMarkUseCase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockMarkUseCase) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMarkUseCaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMarkUseCase)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockMarkUseCase) Get(arg0 context.Context, arg1 string) (*models.Mark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Mark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMarkUseCaseMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMarkUseCase)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockMarkUseCase) List(arg0 context.Context, arg1 *models.MarkFilter) ([]*models.Mark, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Mark)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockMarkUseCaseMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMarkUseCase)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockMarkUseCase) Update(arg0 context.Context, arg1 *models.MarkUpdate) (*models.Mark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*models.Mark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMarkUseCaseMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMarkUseCase)(nil).Update), arg0, arg1)
}
