// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/repositories (interfaces: ApproachRepository)

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockApproachRepository is a mock of ApproachRepository interface.
type MockApproachRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApproachRepositoryMockRecorder
}

// MockApproachRepositoryMockRecorder is the mock recorder for MockApproachRepository.
type MockApproachRepositoryMockRecorder struct {
	mock *MockApproachRepository
}

// NewMockApproachRepository creates a new mock instance.
func NewMockApproachRepository(ctrl *gomock.Controller) *MockApproachRepository {
	mock := &MockApproachRepository{ctrl: ctrl}
	mock.recorder = &MockApproachRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApproachRepository) EXPECT() *MockApproachRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockApproachRepository) Count(arg0 context.Context, arg1 *models.ApproachFilter) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockApproachRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockApproachRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockApproachRepository) Create(arg0 context.Context, arg1 *models.Approach) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApproachRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApproachRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockApproachRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApproachRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApproachRepository)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockApproachRepository) Get(arg0 context.Context, arg1 string) (*models.Approach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Approach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApproachRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApproachRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockApproachRepository) List(arg0 context.Context, arg1 *models.ApproachFilter) ([]*models.Approach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Approach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApproachRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApproachRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockApproachRepository) Update(arg0 context.Context, arg1 *models.Approach) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApproachRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApproachRepository)(nil).Update), arg0, arg1)
}
