// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/repositories (interfaces: ArchRepository)

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockArchRepository is a mock of ArchRepository interface.
type MockArchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArchRepositoryMockRecorder
}

// MockArchRepositoryMockRecorder is the mock recorder for MockArchRepository.
type MockArchRepositoryMockRecorder struct {
	mock *MockArchRepository
}

// NewMockArchRepository creates a new mock instance.
func NewMockArchRepository(ctrl *gomock.Controller) *MockArchRepository {
	mock := &MockArchRepository{ctrl: ctrl}
	mock.recorder = &MockArchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchRepository) EXPECT() *MockArchRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockArchRepository) Count(arg0 context.Context, arg1 *models.ArchFilter) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockArchRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockArchRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockArchRepository) Create(arg0 context.Context, arg1 *models.Arch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockArchRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockArchRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockArchRepository) Delete(arg0 context.Context, arg1 models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArchRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArchRepository)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockArchRepository) Get(arg0 context.Context, arg1 models.UUID) (*models.Arch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Arch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockArchRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockArchRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockArchRepository) List(arg0 context.Context, arg1 *models.ArchFilter) ([]*models.Arch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Arch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockArchRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockArchRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockArchRepository) Update(arg0 context.Context, arg1 *models.Arch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockArchRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArchRepository)(nil).Update), arg0, arg1)
}
