// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/repositories (interfaces: MarkRepository)

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMarkRepository is a mock of MarkRepository interface.
type MockMarkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMarkRepositoryMockRecorder
}

// MockMarkRepositoryMockRecorder is the mock recorder for MockMarkRepository.
type MockMarkRepositoryMockRecorder struct {
	mock *MockMarkRepository
}

// NewMockMarkRepository creates a new mock instance.
func NewMockMarkRepository(ctrl *gomock.Controller) *MockMarkRepository {
	mock := &MockMarkRepository{ctrl: ctrl}
	mock.recorder = &MockMarkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarkRepository) EXPECT() *MockMarkRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockMarkRepository) Count(arg0 context.Context, arg1 *models.MarkFilter) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockMarkRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockMarkRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockMarkRepository) Create(arg0 context.Context, arg1 *models.Mark) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMarkRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMarkRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockMarkRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMarkRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMarkRepository)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockMarkRepository) Get(arg0 context.Context, arg1 string) (*models.Mark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Mark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMarkRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMarkRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockMarkRepository) List(arg0 context.Context, arg1 *models.MarkFilter) ([]*models.Mark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Mark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMarkRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMarkRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockMarkRepository) Update(arg0 context.Context, arg1 *models.Mark) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMarkRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMarkRepository)(nil).Update), arg0, arg1)
}
