// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/example/internal/domain/repositories (interfaces: PlanRepository)

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/example/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockPlanRepository is a mock of PlanRepository interface.
type MockPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepositoryMockRecorder
}

// MockPlanRepositoryMockRecorder is the mock recorder for MockPlanRepository.
type MockPlanRepositoryMockRecorder struct {
	mock *MockPlanRepository
}

// NewMockPlanRepository creates a new mock instance.
func NewMockPlanRepository(ctrl *gomock.Controller) *MockPlanRepository {
	mock := &MockPlanRepository{ctrl: ctrl}
	mock.recorder = &MockPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepository) EXPECT() *MockPlanRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockPlanRepository) Count(arg0 context.Context, arg1 *models.PlanFilter) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPlanRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPlanRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockPlanRepository) Create(arg0 context.Context, arg1 *models.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPlanRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPlanRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockPlanRepository) Delete(arg0 context.Context, arg1 models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlanRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlanRepository)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockPlanRepository) Get(arg0 context.Context, arg1 models.UUID) (*models.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPlanRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPlanRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockPlanRepository) List(arg0 context.Context, arg1 *models.PlanFilter) ([]*models.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPlanRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPlanRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockPlanRepository) Update(arg0 context.Context, arg1 *models.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPlanRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPlanRepository)(nil).Update), arg0, arg1)
}
